version: '3.8'

services:
  redpanda:
    image: docker.redpanda.com/vectorized/redpanda:v22.2.2
    command:
      - redpanda start
      - --smp 1
      - --overprovisioned
      - --node-id 0
      - --kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --advertise-kafka-addr PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9392
      - --pandaproxy-addr redpanda:8082
      - --advertise-pandaproxy-addr localhost:8082
    expose:
      - "8081"
      - "8082"
      - "29092"
      - "9644"
    ports:
      - "9092:9092"
    networks:
      - project

  console:
    image: docker.redpanda.com/vectorized/console:latest
    entrypoint: /bin/sh
    command: -c "echo \"$$CONSOLE_CONFIG_FILE\" > /tmp/config.yml; /app/console"
    environment:
      CONFIG_FILEPATH: /tmp/config.yml
      CONSOLE_CONFIG_FILE: |
        kafka:
          brokers: ["redpanda:29092"]
          schemaRegistry:
            enabled: true
            urls: ["http://redpanda:8081"]
        redpanda:
          adminApi:
            enabled: true
            urls: ["http://redpanda:9644"]
        connect:
          enabled: true
          clusters:
            - name: local-connect-cluster
              url: http://connect:8083
    ports:
      - "8080:8080"
    depends_on:
      - redpanda
    networks:
      - project
  
  app:
    build: .
    container_name: topic_app
    ports:
      - "8000:8000"
    depends_on:
      - redpanda
    networks:
      - project
    environment:
      - KAFKA_HOST=redpanda:29092  
      - KAFKA_API_HOST=redpanda:9092
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 
      - CLICKHOUSE_HOST=http://clickhouse-server:8123 

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.10
    environment:
      discovery.type: single-node
      network.host: 0.0.0.0
      bootstrap.memory_lock: "true"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - project

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.10
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - project

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse-server-2
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./data:/var/lib/clickhouse
      - ./logs:/var/log/clickhouse-server
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
      - SYS_PTRACE
    ports:
      - "9000:9000"  
      - "8123:8123" 
      - "9009:9009"  
    networks:
      - project

networks:
  project:
    name: redpanda


